chore: export userInputValidationSchema
Linkta-org/core pull request #143
Opened 2024-05-30 21:20 UTC by danielboisselle

2024-05-31 00:46 UTC, zhiyi15 commented on utils/zodSchema/userInputValidation.ts
> +export const userInputValidationSchema = z.object({
we probably don't need to export userInputValidationSchema twice here.

2024-06-01 05:59 UTC, relandboyle requested changes
@danielboisselle You've got two export statements for the same variable.

2024-06-03 23:43 UTC, zhiyi15 approved these changes

2024-06-03 23:43 UTC, relandboyle approved these changes

2024-06-03 23:44 UTC, merged