implemented react query for fetching linktaflow
Linkta-org/core pull request #272
Opened 2024-06-27 18:21 UTC by kinskiwu

## Description

Fixes # (issue)

## Type of change

- [ ]  🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨  New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 Documentation update
- [ ] Other 🗒️ ______________

## How Can this be tested? Testing Plan to review this PR

- [ ] Where in the app does this change take place?
- [ ] What are the steps to test this change?
- [ ] What is the expected output?

## Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [ ] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [ ] I have ensured that my pull request title is descriptive.

## Additional Information:

2024-06-27 21:48 UTC, relandboyle requested changes
@kinskiwu I'm running this now, and I can see the path in the address bar changing to include the ObjectId for the particular LinktaFlow object.

I'm also getting lots of errors in the browser console. I'm not sure if they have anything to do with your changes on this PR but I'd like to review together.

I'm noticing that the regenerate logic seems to run on clicking any of the flow titles in the side bar, rather than when clicking the Regenerate button on the flyout menu. Is this the desired behavior?

2024-06-27 21:57 UTC, kinskiwu commented
@relandboyle I wonder if the errors come from the merge conflicts after the recent dev merge because it was clean when I submitted the PR. Also there was no regenerate logic implemented on the menu, let me check the branch and see why it behaves this way.

2024-06-27 23:01 UTC, relandboyle approved these changes

2024-06-28 02:03 UTC, colinvandergraaf approved these changes
LGTM!

2024-06-28 02:46 UTC, merged