Implement 404 page
Linkta-org/core pull request #300
Opened 2024-07-04 00:29 UTC by chrisr0892

## Description

- Implemented a 404 page 
- Added button that routes back to home page
- Ensured the 404 page displays correctly on different screen sizes and across major browsers
- Styled the 404 page according to the design guidelines (styles file created under client/styles/layout)
- added Linkta Logo with background removed to assets folder (existing image has slight opaque background)

Fixes #246 

## Type of change

- [ x] ✨  New feature (non-breaking change which adds functionality)

## How Can this be tested? Testing Plan to review this PR

- [x] Where in the app does this change take place?
- client/features/not-found-page/NotFoundPage.tsx
- [x] What are the steps to test this change?
- run `npm run dev`, then try navigating to a route that does not exist.
- [x] What is the expected output?
- 404 page should render, clicking on button should reroute to homepage

## Checklist:

- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [x] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [x] I have ensured that my pull request title is descriptive.

2024-07-04 20:38 UTC, kinskiwu commented on client/features/not-found-page/NotFoundPage.tsx
Thanks for the good work! THe RouteLInk works very smoothly. 

Sorry that I totally forgot to link the design mockup in the ticket. Please find the 404 error mockup under 'Lo-fi Mockups - MVP' in this link https://www.figma.com/design/9QKsvDQ9jivgA9XfS0oqPd/Design-System---Linkta?node-id=691-3754&t=LIJGGXunTgU93zzD-0 and update the page.

2024-07-04 20:41 UTC, kinskiwu commented on client/styles/layout/NotFoundPage.module.css
The styling looks pretty good! Would be nicer if the content is centered in the viewpoint. You may also want to lower the opacity of the text and button the same way as in the mockup.

2024-07-04 20:46 UTC, kinskiwu reviewed
Great work on your first ticket! Just some small changes related to design and styling. Also you may want to rebase your branch and resolve any merge conflicts (let us know if you need any help with that because it could be a bit tedious).

2024-07-05 03:41 UTC, kinskiwu commented on client/styles/layout/NotFoundPage.module.css
I think this file should be outside of `/layout`

2024-07-05 19:32 UTC, kinskiwu approved these changes
Nice work! Pls remove the unused png inside /public then this pr is good to merge.

2024-07-08 03:08 UTC, relandboyle requested changes
@chrisr0892 This looks really good. Apologies in advance for all the things I'm going to ask you to change...

In the diffs for this PR it looks like you created both the ErrorPage component and stylesheet and the NotFoundPage component and stylesheet. Is that accurate? Or is that a side effect of some Git action that didn't go according to plan? As Kinski commented, please reach out if you need help merging or rebasing to get your branch prepared for review.

In the NotFoundPage.tsx component, I think you could achieve the same styling without the additional 'container' div. Also, in a Material UI app we should always use Material UI elements when possible. That means Box rather than Div, and Typography rather than h1, h2, and paragraph. I think you'll quickly grasp the approach if you review the MUI docs page for [Typography](https://mui.com/material-ui/react-typography/). 

In the NotFoundPage.module.css file, at the top I see a commented-out rule that looks like it was meant to be a temporary / experimental rule. I'm also noticing that you have some rules relating to headings and paragraphs which are not being applied. Those can be removed, and then when you implement the Typography elements you can use css modules if you need to override default styles.

2024-07-19 18:17 UTC, relandboyle approved these changes

2024-07-19 18:17 UTC, merged