Replaced Mock User ID with Real ID and Implemented User Service
Linkta-org/core pull request #307
Opened 2024-07-06 04:54 UTC by kinskiwu

## Description
- All mock user IDs in the API are replaced with real user IDs.
- The new user creation service is implemented and functional.
- The application correctly handles user IDs during signup and subsequent interactions.

Fixes #289 

## Type of change
- [X] ✨  New feature (non-breaking change which adds functionality)

## How Can this be tested? Testing Plan to review this PR
- [ ] Where in the app does this change take place?
- [ ] What are the steps to test this change?
- [ ] What is the expected output?

## Checklist:
- [X] I have performed a self-review of my own code.
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [X] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [X] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [X] I have ensured that my pull request title is descriptive.

2024-07-06 18:04 UTC, LucieSeidler reviewed
The user information in the top left still reads test-user

2024-07-06 18:04 UTC, LucieSeidler commented on server/controllers/genAiController.ts
I'm not sure I understand why this was deleted

2024-07-06 19:53 UTC, kinskiwu commented on server/controllers/genAiController.ts
Good call. I shouldnt have removed it.

2024-07-10 16:00 UTC, LucieSeidler approved these changes
Comment for testers : make sure you sign up before you sign in

2024-07-10 16:15 UTC, kinskiwu commented
@LucieSeidler and I identified that when a user signs up, the path correctly switches to /generate, but sometimes the UI continues to display the auth page. Since this issue doesn't impact the functionality of this feature I created a bug ticket for it #313

2024-07-11 15:44 UTC, relandboyle commented
> @LucieSeidler and I identified that when a user signs up, the path correctly switches to /generate, but sometimes the UI continues to display the auth page. Since this issue doesn't impact the functionality of this feature I created a bug ticket for it #313

@kinskiwu Are you able to confirm that this bug is not introduced by this PR? I have not experienced the described behavior or heard of anyone else experiencing it on another branch.

2024-07-11 16:10 UTC, relandboyle requested changes
> @LucieSeidler and I identified that when a user signs up, the path correctly switches to /generate, but sometimes the UI continues to display the auth page. Since this issue doesn't impact the functionality of this feature I created a bug ticket for it #313

Are we accounting for valid cookies remaining on the browser as we are testing behaviors with multiple users? I ask because the behavior you're describing sounds like what I see happening when log in, leave the site without logging out, and then return to the site. I'm seeing the static layout for logged-in users, but I'm not being redirected to the correct route / view, and I'm seeing numerous logs from the User Service showing "User not found". I'm also seeing the authentication middleware logging my correct UID, so there's clearly some logical disconnect here.

Login / logout, authentication, and router redirects appear to be behaving normally in the dev branch, so I think it's fair to say there is a regression in this branch and it should not be merged as-is.

Please involve @colinvandergraaf and/or myself so we can identify and correct the regression. 

2024-07-11 11:51:08:491 [DEBUG] [UserService] services\userService.ts 18:14 Object.findUserByUid
 Finding user with UID: (my correct Google UID displays here)       

2024-07-11 11:51:08:563 [WARN] [UserService] services\userService.ts 23:16 Object.findUserByUid
 User not found.

2024-07-11 11:51:08:564 [DEBUG] [User Controller] controllers\userController.ts 28:14 fetchUserProfile
 Fetching user profile for userId: undefineddd

2024-07-11 11:51:08:564 [DEBUG] [UserService] services\userService.ts 45:14 Object.findUserById
 Finding user with userId: undefined

2024-07-11 11:51:08:574 [WARN] [UserService] services\userService.ts 23:16 Object.findUserByUid
 User not found.

2024-07-11 11:51:08:575 [DEBUG] [Input Controller] controllers\userInputController.ts 118:14 fetchInputHistory        
 Fetching input history for user: undefined

2024-07-11 11:51:08:575 [DEBUG] [UserInput Service] services\userInputService.ts 60:14 Object.fetchInputHistory       
 Fetching input history { userId: undefined, page: 1, limit: 5, skip: 0 }

2024-07-11 11:51:08:647 [WARN] [UserService] services\userService.ts 50:16 Object.findUserById
 User not found.

2024-07-11 11:51:08:659 [DEBUG] [Input Controller] controllers\userInputController.ts 130:14 fetchInputHistory        
 Fetched input history: []

2024-07-11 17:47 UTC, kinskiwu commented
@relandboyle This error appears when we use an account previously signed up with linkta before this feature was implemented. In this new feature, a user profile is created after signing up (which we didn't have previously thus it is showing a user profile not found error). To test this feature, please first sign up with your account.

2024-07-11 20:03 UTC, relandboyle commented
@kinskiwu I deleted my accounts from Firebase and I'm seeing the same or similar behavior.

Can we schedule a Zoom discussion / review for this? Continued via Slack...

2024-07-12 15:25 UTC, kinskiwu commented
Converting this PR to draft to fix some issues

2024-07-12 20:56 UTC, relandboyle approved these changes
Nice.

2024-07-12 20:57 UTC, merged

2024-07-12 22:11 UTC, kinskiwu commented
Just fyi in case any of you are following this PR:
- @relandboyle @ejwoods @chrisr0892 and I had a live pair programming session today and we were able to identify and fix a couple of issues causing the errors.

- Changes I made to fix the residual SignUp Page issue: I added a userEffect to redirect a user to `/generate’  when a user is authenticated
- Changes I made to ensure a user signing in through oauth gets a new userprofile generated:  updated handleGoogleAuthCick & handleGithubAuthClick to create a new userProfile if it is nonexistent upon sign-in