feat(#385): Consistent yellow pill buttons
Linkta-org/core pull request #402
Opened 2024-09-27 00:49 UTC by chriswillsflannery

## Updates all yellow pill buttons to match Log In / Log Out buttons (that is, "secondary-main" color normally, and "secondary-dark" on hover, and text color "secondary" regardless of hover state).

Partially Fixes #385 

## Type of change

🐛 Bug fix (non-breaking change which fixes an issue)

Sign In / Sign Up / Save
![Screenshot from 2024-09-26 20-25-33](https://github.com/user-attachments/assets/4cb285fa-2d2b-42a8-aadd-f92e39388843)

404 page
![Screenshot from 2024-09-26 20-25-45](https://github.com/user-attachments/assets/a67504d3-9e49-4d8f-8695-1b32090837dc)

Error Page
![Screenshot from 2024-09-26 20-28-16](https://github.com/user-attachments/assets/9d764b2c-1a5d-4f2f-aa7f-7cdb92affe89)

Sign In Page
![Screenshot from 2024-09-26 20-35-44](https://github.com/user-attachments/assets/bfd069c2-6b9c-4e57-88c9-c7ef6e62e611)

Create Account Page
![Screenshot from 2024-09-26 20-46-05](https://github.com/user-attachments/assets/a7724803-ab85-4368-b278-712acb4334f0)

Send Link Page
![Screenshot from 2024-09-26 20-38-35](https://github.com/user-attachments/assets/c1202c37-c152-4134-8a8b-da9f3c178dfb)

Generate
![Screenshot from 2024-09-26 20-47-10](https://github.com/user-attachments/assets/38b71aa2-58e4-45cb-9218-89d5bb1efcfb)

## How Can this be tested? Testing Plan to review this PR

User should review the above pages and ensure:
1. Medium yellow color normally
2. Darker color on hover

2024-09-27 17:31 UTC, relandboyle requested changes
@chriswillsflannery This looks great.

A lot of this may have been in the app before you started but there seems to be some consistent redundancy in button styles. I'm seeing a style applied in-line on an element, and also applied via the CSS modules. For example, the 'color' property on an MUI button is redundant with the 'background-color' property applied via the '.button' selector.

![image](https://github.com/user-attachments/assets/d32a2bf8-d839-4a36-999c-2668a2be1869)

2024-10-01 01:53 UTC, chriswillsflannery commented
ok @relandboyle I just pushed an update which:
- prefers using css modules as the source of truth for any background color/text color styling
- all yellow buttons have primary dark text, and will show darker yellow color on hover
- also included the confirmation dialog "save" buttons which I missed on the first pass

2024-10-02 00:44 UTC, kinskiwu approved these changes
LGTM! Thanks for fixing the color bug!

2024-10-02 09:53 UTC, relandboyle approved these changes

2024-10-02 17:01 UTC, merged