Fix/linkta 169 no relative import paths configuration in eslintrc breaks node nodemon
Linkta-org/core pull request #41
Opened 2024-03-21 03:24 UTC by dcpavel

## Description

This merge adds another module and some configuration to tsconfig.json to allow for path aliases to be used. It also allows linting to not allow relative import paths.

Fixes # (LINKTA-169)[https://linkta.atlassian.net/browse/LINKTA-169]

## Type of change

- [x]  🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨  New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 Documentation update
- [ ] Other 🗒️ ______________

## How Has This Been Tested?

Manual testing for now.

## Checklist:

- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I have reviewed the [**Security Best Practices Document**](SECURITY_BEST_PRACTICES.md).
- [x] I have followed the [**Naming Conventions Guide**](NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [x] I have ensured that my pull request title is descriptive.

## Additional Information:

2024-03-21 03:25 UTC, dcpavel commented
This fix encorporates changes on the adding linter to GitHub Actions change: https://github.com/Linkta-org/core/pull/33

This should occur after that.

2024-03-21 15:16 UTC, LucieSeidler requested changes
Did you mean to merge into main?

2024-03-21 17:17 UTC, dcpavel commented
I did not mean to merge into main. Changing now.

2024-03-22 15:56 UTC, LucieSeidler approved these changes

2024-03-22 18:39 UTC, ChTiSh approved these changes

2024-03-22 18:39 UTC, merged