Feature/linkta 91 back end formats prompt and communicates with gemini
Linkta-org/core pull request #64
Opened 2024-03-27 20:28 UTC by dcpavel

## Description

This changes the /gen-ai/query route to convert the prompt into a form that will return a response from the LLM that can be used to generate a tree.

There are a number of prompt examples to use, which may need to be modified. This has been done so that testing can be implemented in order to expand types and test different prompts to determine the best results.

## Type of change

- [ ]  🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨  New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 Documentation update
- [ ] Other 🗒️ ______________

## How Has This Been Tested?

Manual testing.

## Checklist:

- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [x] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [x] I have ensured that my pull request title is descriptive.

## Additional Information:

There is work here that is meant to be built upon as needed in the future. A test of the current configuration gave this response:
"```JSON\n{\n  \"Architecture\": {\n    \"History\": [\n      \"Ancient Egypt\",\n      \"Ancient Greece\",\n      \"Ancient Rome\",\n      \"Byzantium\",\n      \"Renaissance\",\n      \"Baroque\",\n      \"Neoclassicism\",\n      \"Modernism\",\n      \"Postmodernism\"\n    ],\n    \"Building Types\": [\n      \"Residential\",\n      \"Commercial\",\n      \"Institutional\",\n      \"Civic\",\n      \"Industrial\",\n      \"Religious\",\n      \"Military\"\n    ],\n    \"Design Elements\": [\n      \"Form\",\n      \"Function\",\n      \"Structure\",\n      \"Materials\",\n      \"Light\",\n      \"Color\",\n      \"Texture\"\n    ],\n    \"Sustainable Design\": [\n      \"Green Building\",\n      \"Environmental Impact\",\n      \"Renewable Energy\",\n      \"Water Conservation\",\n      \"Waste Reduction\"\n    ],\n    \"Architectural Styles\": [\n      \"Classical\",\n      \"Gothic\",\n      \"Renaissance\",\n      \"Baroque\",\n      \"Neoclassicism\",\n      \"Modernism\",\n      \"Postmodernism\"\n    ]\n  }\n}\n```"

We are still not transforming this response into a tree, that is a separate issue.

2024-03-28 16:54 UTC, dcpavel commented
Added the edge case I mentioned in standups.

2024-04-01 22:18 UTC, kinskiwu approved these changes
Small changes. The rest looks good to me😊

2024-04-01 22:18 UTC, kinskiwu commented on server/utils/typeChecker.ts
- Line 13: did you mean to return false when the lengths are not equal? 
- Consider renaming `isType` to a more descriptive name (sth like isValidAIInputType?) to more accurately reflect its role in validating complex input types for AI operations. 
- It appears that `isType` only checks the types for one layer of properties, do we also need the capability to check types for nested objects? I wonder if using a validation library like zod or joi may make type checking easier.
- Have we handled the edge case when prompt input is null? (in JS type of null is also an object)

2024-04-01 22:18 UTC, kinskiwu commented on server/controllers/genAiController.ts
> +import { AIProvider } from '@server/types/index';
Maybe `AIProvider` can be grouped with the import from line 8?

2024-04-01 22:18 UTC, kinskiwu commented on server/controllers/genAiController.ts
Consider adding null checks and validate inputs for request payloads.

2024-04-01 22:26 UTC, dcpavel commented on server/controllers/genAiController.ts
Good idea.

2024-04-02 17:33 UTC, LucieSeidler requested changes

2024-04-02 17:33 UTC, LucieSeidler commented on server/utils/typeChecker.ts
second this question

2024-05-07 18:11 UTC, LucieSeidler approved these changes

2024-05-07 19:37 UTC, kinskiwu commented on server/controllers/genAiController.ts
> +import { AIProvider } from '@server/types/index';
AIProvider is not a type. Disregard this comment.

2024-05-09 19:39 UTC, merged